include_guard()

if(ARCHIMEDES_BUILD_EXAMPLES)

include("${PROJECT_SOURCE_DIR}/cmake/library.cmake")

set(EXAMPLES_DIR "${PROJECT_SOURCE_DIR}/examples")

file(GLOB EXAMPLES_CATEGORIES RELATIVE ${EXAMPLES_DIR} "${EXAMPLES_DIR}/*")
	
foreach(EXAMPLE_CATEGORY ${EXAMPLES_CATEGORIES})
	set(EXAMPLE_CATEGORY_PATH "${EXAMPLES_DIR}/${EXAMPLE_CATEGORY}")
	
	file(GLOB EXAMPLES RELATIVE ${EXAMPLE_CATEGORY_PATH} "${EXAMPLE_CATEGORY_PATH}/*")

	foreach(EXAMPLE ${EXAMPLES})
		set(EXAMPLE_PATH "${EXAMPLE_CATEGORY_PATH}/${EXAMPLE}")
		if(IS_DIRECTORY ${EXAMPLE_PATH})
			file(GLOB_RECURSE EXAMPLE_SOURCES "${EXAMPLE_PATH}/**.cpp")

			set(EXAMPLE_TARGET "${EXAMPLE_CATEGORY}-${EXAMPLE}")
			add_executable(${EXAMPLE_TARGET} ${EXAMPLE_SOURCES})
			target_link_libraries(${EXAMPLE_TARGET} PUBLIC ${PROJECT_NAME})
			target_precompile_headers(${EXAMPLE_TARGET} REUSE_FROM ${PROJECT_NAME})
			set_property(TARGET ${EXAMPLE_TARGET} PROPERTY INTERPROCEDURAL_OPTIMIZATION TRUE)
			
			LaunchAddTarget(${EXAMPLE_TARGET})
		endif()
	endforeach()
endforeach()

endif()