#pragma once

#include <cmath>

namespace arch::font {

/// @brief Contains data read from json generated by msdf-atlas-gen
struct GlyphData {
	/// @brief Next glyph position on X axis relative to current glyph
	float advance = std::nan("");

	/// @brief Rectangle type
	struct Rect {
		float left = std::nan("");
		float top = std::nan("");
		float right = std::nan("");
		float bottom = std::nan("");
	};

	/// @brief Glyph bounds relative to base
	Rect planeBounds;

	/// @brief Glyph position in generated atlas PNG
	Rect atlasBounds;

	/// @brief UV type
	struct UV {
		/// @brief 2D Vector type
		struct Vec {
			float x = std::nan("");
			float y = std::nan("");
		};

		/// @brief Top-left UV corner
		Vec first;
		/// @brief Bottom-right UV corner
		Vec second;
	};

	/// @brief UV data (texCoords)
	UV uv;

	/// @brief Glyph width in atlas PNG
	float width = std::nan("");
	/// @brief Glyph height in atlas PNG
	float height = std::nan("");

	/// @brief Checks if this glyph has only advance field
	bool advanceOnly() const noexcept;
};

} // namespace arch::font
