include_guard()

# yyyy.mm.dd: 4(y) + 4(m/d) + 2(.) = 10 chars
file(READ "version.txt" ARCHIMEDES_VERSION)
string(STRIP ${ARCHIMEDES_VERSION} ARCHIMEDES_VERSION)

if(NOT ARCHIMEDES_VERSION MATCHES "^[0-9]+\.[0-9]+\.[0-9]+$")
	message(FATAL_ERROR "'${ARCHIMEDES_VERSION}' is not a valid version")
endif()

# Parse & set version
string(FIND "${ARCHIMEDES_VERSION}" "." VERSION_FIRST_DOT_POS)
string(FIND "${ARCHIMEDES_VERSION}" "." VERSION_SECOND_DOT_POS REVERSE)

math(EXPR VERSION_MINOR_POS "${VERSION_FIRST_DOT_POS}+1")
math(EXPR VERSION_MINOR_LENGTH "${VERSION_SECOND_DOT_POS}-${VERSION_FIRST_DOT_POS}-1")
math(EXPR VERSION_PATCH_POS "${VERSION_SECOND_DOT_POS}+1")

string(SUBSTRING "${ARCHIMEDES_VERSION}" 0 ${VERSION_FIRST_DOT_POS} ARCHIMEDES_VERSION_MAJOR)
string(SUBSTRING "${ARCHIMEDES_VERSION}" ${VERSION_MINOR_POS} ${VERSION_MINOR_LENGTH} ARCHIMEDES_VERSION_MINOR)
string(SUBSTRING "${ARCHIMEDES_VERSION}" ${VERSION_PATCH_POS} -1 ARCHIMEDES_VERSION_PATCH)
