name: NVRHI build test

on:
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CONAN_LOGIN_USERNAME: chris++
      CONAN_PASSWORD: ${{ secrets.CONAN_TOKEN }}
      CONAN_REMOTE_NAME: conan_coin
      CONAN_REMOTE_URL: https://artifactory.coin.agh.edu.pl/artifactory/api/conan/conan-local

    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Test GCC & CMake
        run: |
          gcc --version
          g++ --version
          cmake --version
