name: Toolchain test

on:
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master

jobs:        
  Windows:
    runs-on: windows-2025

    steps:
      - name: Test
        run: |
          gcc --version
          gcc-14 --version
          g++ --version
          g++-14 --version
          clang --version
          clang-20 --version
          clang++ --version
          clang++-20 --version
          cl --version
